[project]
name = "doremon-e103a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "google-genai>=1.56.0",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
